### ISSUE TITLE
Using embedded progress with spring-cloud-contract

### ISSUE THREAD

**Issue by SrDiro** [zonkyio/embedded-postgres#35]
Hi,

I'm trying to use spring-cloud-contract-maven-plugin in a spring application to test my controllers.
But when I try to compile and to accomplish the contracts with mockeds data on SupplyPointStatsContractTest.class I get this error.

`Description:`

`Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.`

`Reason: Failed to determine a suitable driver class`

`Action:`

`Consider the following:`
	`If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.`
	`If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently` `active).`

before I have been using the h2 embedded database, but I have changed it because there are queries that h2 does not support because it is not native postgresql syntax.

Any idea about how to avoid this problem?

**Comment by tomix26** [comment]
Hi,

have you tried https://github.com/zonkyio/embedded-database-spring-test project? Because it is built on `embedded-postgres` library but focused on spring integration tests. So, you only put `@AutoConfigureEmbeddedDatabase` annotation on the test class and that's all. You can also put the annotation on a parent class and share a common configuration between multiple tests. See https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract-maven-plugin/generateTests-mojo.html#baseClassMappings

**Comment by tomix26** [comment]
No response, closing the issue.
